# Generated by Django 4.2.2 on 2023-08-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuslog",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
