# Generated by Django 4.2.2 on 2023-07-05 08:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedFace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time")),
                ("changed_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Last change time")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID identification"
                    ),
                ),
                ("image", models.ImageField(upload_to="crops/%Y/%m/%d/", verbose_name="Image")),
                ("face_id", models.IntegerField(blank=True, null=True, verbose_name="Face identity")),
            ],
            options={
                "verbose_name": "Detected face",
                "verbose_name_plural": "Detected faces",
                "ordering": ("-id", "face_id"),
            },
        ),
        migrations.CreateModel(
            name="FaceRecognitionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time")),
                ("changed_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Last change time")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID identification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face recognition request",
                "verbose_name_plural": "Face recognition requests",
            },
        ),
        migrations.CreateModel(
            name="SimilarPerson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time")),
                ("changed_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Last change time")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID identification"
                    ),
                ),
                ("photo", models.URLField(max_length=1000, verbose_name="Photo")),
                ("distance", models.FloatField(verbose_name="Distance")),
                ("first_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="First name")),
                ("middle_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Middle name")),
                ("last_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Last name")),
                ("iin", models.CharField(max_length=12, verbose_name="Individual identification number")),
                ("id_number", models.CharField(max_length=50, verbose_name="ID number")),
                (
                    "detected_face",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="persons.detectedface",
                        verbose_name="Detected face",
                    ),
                ),
            ],
            options={
                "verbose_name": "Similar person",
                "verbose_name_plural": "Similar persons",
                "ordering": ("-distance",),
            },
        ),
        migrations.CreateModel(
            name="OriginalImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created time")),
                ("changed_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Last change time")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID identification"
                    ),
                ),
                ("image", models.ImageField(upload_to="originals/%Y/%m/%d/", verbose_name="Image")),
                (
                    "unique_id",
                    models.CharField(blank=True, max_length=150, null=True, verbose_name="Identity of result"),
                ),
                ("results_path", models.CharField(max_length=1000, verbose_name="Path to results folder")),
                (
                    "face_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Face identities",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="persons.facerecognitionrequest",
                        verbose_name="Face recognition request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Original image",
                "verbose_name_plural": "Original images",
            },
        ),
        migrations.AddField(
            model_name="detectedface",
            name="original_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faces",
                to="persons.originalimage",
                verbose_name="Original image",
            ),
        ),
    ]
