# Generated by Django 4.2.2 on 2024-01-17 12:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0005_alter_originalimage_face_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="facerecognitionrequest",
            name="description",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="originalimage",
            name="face_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True),
                blank=True,
                default=list,
                size=None,
                verbose_name="Face identities",
            ),
        ),
    ]
