# Generated by Django 4.2.2 on 2023-10-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "iin",
                    models.CharField(blank=True, db_column="gr_code", max_length=255, null=True, verbose_name="IIN"),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, db_column="ud_code", max_length=255, null=True, verbose_name="ID number"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, db_column="firstname", max_length=255, null=True, verbose_name="First name"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, db_column="secondname", max_length=255, null=True, verbose_name="Middle name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_column="lastname", max_length=255, null=True, verbose_name="Last name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
                "db_table": "unique_ud_gr_cache",
            },
        ),
    ]
